/*
 * generated by Xtext
 */
package org.jastemf.siple;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SipleRuntimeModule extends org.jastemf.siple.AbstractSipleRuntimeModule {

}
