/*
* generated by Xtext
*/
package org.jastemf.siple.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SipleOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
