/* Generated By:JJTree: Do not edit this line. ASTAspectRefineConstructorDeclaration.java */

package jrag.AST;

public class ASTAspectRefineConstructorDeclaration extends SimpleNode {
  public ASTAspectRefineConstructorDeclaration(int id) {
    super(id);
  }

  public ASTAspectRefineConstructorDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
