/* Generated By:JJTree: Do not edit this line. ASTAspectRefineMethodDeclarationLookahead.java */

package jrag.AST;

public class ASTAspectRefineMethodDeclarationLookahead extends SimpleNode {
  public ASTAspectRefineMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTAspectRefineMethodDeclarationLookahead(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
