/* Generated By:JJTree: Do not edit this line. ASTAspectBodyDeclaration.java */

package jrag.AST;

public class ASTAspectBodyDeclaration extends SimpleNode {
  public ASTAspectBodyDeclaration(int id) {
    super(id);
  }

  public ASTAspectBodyDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
