/* Generated By:JJTree: Do not edit this line. ASTAspectRefineInhEquation.java */

package jrag.AST;

public class ASTAspectRefineInhEquation extends SimpleNode {
  public ASTAspectRefineInhEquation(int id) {
    super(id);
  }

  public ASTAspectRefineInhEquation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
