/* Generated By:JJTree: Do not edit this line. ASTAspectDeclaration.java */

package jrag.AST;

public class ASTAspectDeclaration extends SimpleNode {
  public ASTAspectDeclaration(int id) {
    super(id);
  }

  public ASTAspectDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
