/* Generated By:JJTree: Do not edit this line. ASTAspectInterfaceDeclaration.java */

package jrag.AST;

public class ASTAspectInterfaceDeclaration extends SimpleNode {
  public ASTAspectInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTAspectInterfaceDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
