/* Generated By:JJTree: Do not edit this line. ASTAspectSonsDeclaration.java */

package jrag.AST;

public class ASTAspectSonsDeclaration extends SimpleNode {
  public ASTAspectSonsDeclaration(int id) {
    super(id);
  }

  public ASTAspectSonsDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
