/* Generated By:JJTree: Do not edit this line. ASTAspectClassBody.java */

package jrag.AST;

public class ASTAspectClassBody extends SimpleNode {
  public ASTAspectClassBody(int id) {
    super(id);
  }

  public ASTAspectClassBody(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
