/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeMemberDeclaration.java */

package jrag.AST;

public class ASTAnnotationTypeMemberDeclaration extends SimpleNode {
  public ASTAnnotationTypeMemberDeclaration(int id) {
    super(id);
  }

  public ASTAnnotationTypeMemberDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
