/* Generated By:JJTree: Do not edit this line. ASTAspectMethodDeclarationLookahead.java */

package jrag.AST;

public class ASTAspectMethodDeclarationLookahead extends SimpleNode {
  public ASTAspectMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTAspectMethodDeclarationLookahead(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
