/* Generated By:JJTree: Do not edit this line. ASTAspectExtendInterface.java */

package jrag.AST;

public class ASTAspectExtendInterface extends SimpleNode {
  public ASTAspectExtendInterface(int id) {
    super(id);
  }

  public ASTAspectExtendInterface(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
