/* Generated By:JJTree: Do not edit this line. ASTAspectBody.java */

package jrag.AST;

public class ASTAspectBody extends SimpleNode {
  public ASTAspectBody(int id) {
    super(id);
  }

  public ASTAspectBody(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
