/* Generated By:JJTree: Do not edit this line. ASTAspectInterfaceMethodDeclarationLookahead.java */

package jrag.AST;

public class ASTAspectInterfaceMethodDeclarationLookahead extends SimpleNode {
  public ASTAspectInterfaceMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTAspectInterfaceMethodDeclarationLookahead(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
