/* Generated By:JJTree: Do not edit this line. ASTAspectAddInterface.java */

package jrag.AST;

public class ASTAspectAddInterface extends SimpleNode {
  public ASTAspectAddInterface(int id) {
    super(id);
  }

  public ASTAspectAddInterface(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
