/* Generated By:JJTree: Do not edit this line. ASTAspectInterfaceSynAttributeDeclaration.java */

package jrag.AST;

public class ASTAspectInterfaceSynAttributeDeclaration extends SimpleNode {
  public ASTAspectInterfaceSynAttributeDeclaration(int id) {
    super(id);
  }

  public ASTAspectInterfaceSynAttributeDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
