/* Generated By:JJTree: Do not edit this line. ASTAspectInhAttributeDeclaration.java */

package jrag.AST;

public class ASTAspectInhAttributeDeclaration extends SimpleNode {
  public ASTAspectInhAttributeDeclaration(int id) {
    super(id);
  }

  public ASTAspectInhAttributeDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
