/* Generated By:JJTree: Do not edit this line. ASTClassBody.java */

package jrag.AST;

public class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
