/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java */

package jrag.AST;

public class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
