/* Generated By:JJTree: Do not edit this line. ASTEnumConstant.java */

package jrag.AST;

public class ASTEnumConstant extends SimpleNode {
  public ASTEnumConstant(int id) {
    super(id);
  }

  public ASTEnumConstant(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
