/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java */

package jrag.AST;

public class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
