/* Generated By:JJTree: Do not edit this line. ASTMarkerAnnotation.java */

package jrag.AST;

public class ASTMarkerAnnotation extends SimpleNode {
  public ASTMarkerAnnotation(int id) {
    super(id);
  }

  public ASTMarkerAnnotation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
