/* Generated By:JJTree: Do not edit this line. ASTNameList.java */

package jrag.AST;

public class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
