/* Generated By:JJTree: Do not edit this line. ASTPreDecrementExpression.java */

package jrag.AST;

public class ASTPreDecrementExpression extends SimpleNode {
  public ASTPreDecrementExpression(int id) {
    super(id);
  }

  public ASTPreDecrementExpression(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
