/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java */

package jrag.AST;

public class ASTPackageDeclaration extends SimpleNode {
  public ASTPackageDeclaration(int id) {
    super(id);
  }

  public ASTPackageDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
