/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java */

package jrag.AST;

public class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
