/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java */

package jrag.AST;

public class ASTSingleMemberAnnotation extends SimpleNode {
  public ASTSingleMemberAnnotation(int id) {
    super(id);
  }

  public ASTSingleMemberAnnotation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
