/* Generated By:JJTree: Do not edit this line. ASTTypeArguments.java */

package jrag.AST;

public class ASTTypeArguments extends SimpleNode {
  public ASTTypeArguments(int id) {
    super(id);
  }

  public ASTTypeArguments(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
