/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java */

package jrag.AST;

public class ASTTryStatement extends SimpleNode {
  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
