/* Generated By:JJTree: Do not edit this line. ASTType.java */

package jrag.AST;

public class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
