/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java */

package jrag.AST;

public class ASTWildcardBounds extends SimpleNode {
  public ASTWildcardBounds(int id) {
    super(id);
  }

  public ASTWildcardBounds(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
