/* Generated By:JJTree: Do not edit this line. ASTAspectNestedInterfaceDeclaration.java */

package jrag.AST;

public class ASTAspectNestedInterfaceDeclaration extends SimpleNode {
  public ASTAspectNestedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTAspectNestedInterfaceDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
