/* Generated By:JJTree: Do not edit this line. ASTAspectClassDeclaration.java */

package jrag.AST;

public class ASTAspectClassDeclaration extends SimpleNode {
  public ASTAspectClassDeclaration(int id) {
    super(id);
  }

  public ASTAspectClassDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
