/* Generated By:JJTree: Do not edit this line. ASTAspectFieldDeclaration.java */

package jrag.AST;

public class ASTAspectFieldDeclaration extends SimpleNode {
  public ASTAspectFieldDeclaration(int id) {
    super(id);
  }

  public ASTAspectFieldDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
