/* Generated By:JJTree: Do not edit this line. ASTAspectInterfaceMethodDeclaration.java */

package jrag.AST;

public class ASTAspectInterfaceMethodDeclaration extends SimpleNode {
  public ASTAspectInterfaceMethodDeclaration(int id) {
    super(id);
  }

  public ASTAspectInterfaceMethodDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
