/* Generated By:JJTree: Do not edit this line. ASTAspectMethodDeclaration.java */

package jrag.AST;

public class ASTAspectMethodDeclaration extends SimpleNode {
  public ASTAspectMethodDeclaration(int id) {
    super(id);
  }

  public ASTAspectMethodDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
