/* Generated By:JJTree: Do not edit this line. ASTAspectConstructorDeclaration.java */

package jrag.AST;

public class ASTAspectConstructorDeclaration extends SimpleNode {
  public ASTAspectConstructorDeclaration(int id) {
    super(id);
  }

  public ASTAspectConstructorDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
