/* Generated By:JJTree: Do not edit this line. ASTArrayInitializer.java */

package jrag.AST;

public class ASTArrayInitializer extends SimpleNode {
  public ASTArrayInitializer(int id) {
    super(id);
  }

  public ASTArrayInitializer(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
