/* Generated By:JJTree: Do not edit this line. ASTAspectInhEquation.java */

package jrag.AST;

public class ASTAspectInhEquation extends SimpleNode {
  public ASTAspectInhEquation(int id) {
    super(id);
  }

  public ASTAspectInhEquation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
