/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java */

package jrag.AST;

public class ASTAssertStatement extends SimpleNode {
  public ASTAssertStatement(int id) {
    super(id);
  }

  public ASTAssertStatement(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
