/* Generated By:JJTree: Do not edit this line. ASTAspectNestedClassDeclaration.java */

package jrag.AST;

public class ASTAspectNestedClassDeclaration extends SimpleNode {
  public ASTAspectNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTAspectNestedClassDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
