/* Generated By:JJTree: Do not edit this line. ASTAspectInterfaceFieldDeclaration.java */

package jrag.AST;

public class ASTAspectInterfaceFieldDeclaration extends SimpleNode {
  public ASTAspectInterfaceFieldDeclaration(int id) {
    super(id);
  }

  public ASTAspectInterfaceFieldDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
