/* Generated By:JJTree: Do not edit this line. ASTAspectRefineSynEquation.java */

package jrag.AST;

public class ASTAspectRefineSynEquation extends SimpleNode {
  public ASTAspectRefineSynEquation(int id) {
    super(id);
  }

  public ASTAspectRefineSynEquation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
