/* Generated By:JJTree: Do not edit this line. ASTAspectSynEquation.java */

package jrag.AST;

public class ASTAspectSynEquation extends SimpleNode {
  public ASTAspectSynEquation(int id) {
    super(id);
  }

  public ASTAspectSynEquation(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
