/* Generated By:JJTree: Do not edit this line. ASTAspectRefineMethodDeclaration.java */

package jrag.AST;

public class ASTAspectRefineMethodDeclaration extends SimpleNode {
  public ASTAspectRefineMethodDeclaration(int id) {
    super(id);
  }

  public ASTAspectRefineMethodDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
