/* Generated By:JJTree: Do not edit this line. ASTAspectSynAttributeDeclaration.java */

package jrag.AST;

public class ASTAspectSynAttributeDeclaration extends SimpleNode {
  public ASTAspectSynAttributeDeclaration(int id) {
    super(id);
  }

  public ASTAspectSynAttributeDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
