/* Generated By:JJTree: Do not edit this line. ASTCollectionContribution.java */

package jrag.AST;

public class ASTCollectionContribution extends SimpleNode {
  public ASTCollectionContribution(int id) {
    super(id);
  }

  public ASTCollectionContribution(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
