/* Generated By:JJTree: Do not edit this line. ASTCollectionAttribute.java */

package jrag.AST;

public class ASTCollectionAttribute extends SimpleNode {
  public ASTCollectionAttribute(int id) {
    super(id);
  }

  public ASTCollectionAttribute(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
