/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java */

package jrag.AST;

public class ASTExclusiveOrExpression extends SimpleNode {
  public ASTExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTExclusiveOrExpression(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
