/* Generated By:JJTree: Do not edit this line. ASTFieldModifiers.java */

package jrag.AST;

public class ASTFieldModifiers extends SimpleNode {
  public ASTFieldModifiers(int id) {
    super(id);
  }

  public ASTFieldModifiers(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
