/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java */

package jrag.AST;

public class ASTInstanceOfExpression extends SimpleNode {
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
