/* Generated By:JJTree: Do not edit this line. ASTInterfaceMemberDeclaration.java */

package jrag.AST;

public class ASTInterfaceMemberDeclaration extends SimpleNode {
  public ASTInterfaceMemberDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceMemberDeclaration(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
