/* Generated By:JJTree: Do not edit this line. ASTMemberValue.java */

package jrag.AST;

public class ASTMemberValue extends SimpleNode {
  public ASTMemberValue(int id) {
    super(id);
  }

  public ASTMemberValue(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
