/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java */

package jrag.AST;

public class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
