/* Generated By:JJTree: Do not edit this line. ASTSynchronizedStatement.java */

package jrag.AST;

public class ASTSynchronizedStatement extends SimpleNode {
  public ASTSynchronizedStatement(int id) {
    super(id);
  }

  public ASTSynchronizedStatement(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
