/* Generated By:JJTree: Do not edit this line. ASTTypeArgument.java */

package jrag.AST;

public class ASTTypeArgument extends SimpleNode {
  public ASTTypeArgument(int id) {
    super(id);
  }

  public ASTTypeArgument(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
