/* Generated By:JJTree: Do not edit this line. ASTTypeBound.java */

package jrag.AST;

public class ASTTypeBound extends SimpleNode {
  public ASTTypeBound(int id) {
    super(id);
  }

  public ASTTypeBound(JragParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JragParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
