/* Generated By:JJTree&JavaCC: Do not edit this line. AstConstants.java */
package ast.AST;

public interface AstConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int SEMICOLON = 14;
  int BOOLEAN = 15;
  int CHAR = 16;
  int BYTE = 17;
  int SHORT = 18;
  int INT = 19;
  int LONG = 20;
  int FLOAT = 21;
  int DOUBLE = 22;
  int SUPER = 23;
  int EXTENDS = 24;
  int ID = 25;
  int LETTER = 26;
  int DIGIT = 27;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\";\"",
    "\"boolean\"",
    "\"char\"",
    "\"byte\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"super\"",
    "\"extends\"",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\"::=\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"<\"",
    "\"]\"",
    "\">\"",
    "\".\"",
    "\",\"",
    "\"?\"",
  };

}
