/* Generated By:JJTree: Do not edit this line. .\src-gen\ast\AST\AstTreeConstants.java */

package ast.AST;

public interface AstTreeConstants
{
  public int JJTGRAMMAR = 0;
  public int JJTLIST = 1;
  public int JJTASTDECL = 2;
  public int JJTOPT = 3;
  public int JJTVOID = 4;
  public int JJTABSTRACT = 5;
  public int JJTLISTCOMPONENTS = 6;
  public int JJTLISTCOMPONENTSNTA = 7;
  public int JJTOPTIONALCOMPONENT = 8;
  public int JJTOPTIONALCOMPONENTNTA = 9;
  public int JJTTOKENCOMPONENT = 10;
  public int JJTTOKENCOMPONENTNTA = 11;
  public int JJTAGGREGATECOMPONENTS = 12;
  public int JJTAGGREGATECOMPONENTSNTA = 13;
  public int JJTID = 14;
  public int JJTNAMENODE = 15;
  public int JJTIDUSE = 16;
  public int JJTIDDECL = 17;
  public int JJTTOKENID = 18;


  public String[] jjtNodeName = {
    "Grammar",
    "List",
    "ASTDecl",
    "Opt",
    "void",
    "Abstract",
    "ListComponents",
    "ListComponentsNTA",
    "OptionalComponent",
    "OptionalComponentNTA",
    "TokenComponent",
    "TokenComponentNTA",
    "AggregateComponents",
    "AggregateComponentsNTA",
    "Id",
    "NameNode",
    "IdUse",
    "IdDecl",
    "TokenId",
  };
}
