/* Generated By:JJTree: Do not edit this line. .\src-gen\ast\AST\AstVisitor.java */

package ast.AST;

public interface AstVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Grammar node, Object data);
  public Object visit(List node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(Opt node, Object data);
  public Object visit(Abstract node, Object data);
  public Object visit(ListComponents node, Object data);
  public Object visit(ListComponentsNTA node, Object data);
  public Object visit(OptionalComponent node, Object data);
  public Object visit(OptionalComponentNTA node, Object data);
  public Object visit(TokenComponent node, Object data);
  public Object visit(TokenComponentNTA node, Object data);
  public Object visit(AggregateComponents node, Object data);
  public Object visit(AggregateComponentsNTA node, Object data);
  public Object visit(Id node, Object data);
  public Object visit(NameNode node, Object data);
  public Object visit(IdUse node, Object data);
  public Object visit(IdDecl node, Object data);
  public Object visit(TokenId node, Object data);
}
