<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="http://www.jastemf.org/test" nsPrefix="test">
  <eSubpackages name="ntas" nsURI="http://www.jastemf.org/test/ntas" nsPrefix="ntas">
    <eClassifiers xsi:type="ecore:EClass" name="Root">
      <eStructuralFeatures xsi:type="ecore:EReference" name="derivedA" lowerBound="1"
          eType="#//ntas/A" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="derivedB" upperBound="-1"
          eType="#//ntas/B" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containmentC" lowerBound="1"
          eType="#//ntas/C" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containmentD" upperBound="-1"
          eType="#//ast/D" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="myA" eType="#//ntas/A"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B"/>
    <eClassifiers xsi:type="ecore:EClass" name="C">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="someTerminal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ast" nsURI="http://www.jastemf.org/test/ast" nsPrefix="ast">
    <eClassifiers xsi:type="ecore:EClass" name="D" eSuperTypes="#//ast/AbstractD">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lowerD" lowerBound="1"
          eType="#//ast/D" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="UpperC" lowerBound="1"
          eType="#//ntas/C" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multipleLowerD" upperBound="-1"
          eType="#//ast/D" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MultipleUpperC" upperBound="-1"
          eType="#//ntas/C" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DerivedUpperD" lowerBound="1"
          eType="#//ast/D" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DerivedMultipleUpperC"
          upperBound="-1" eType="#//ntas/C" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="someQCollection" lowerBound="1"
          eType="#//ast/QCollection"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="someCollection" eType="#//ast/Collection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="QCollection" instanceClassName="java.util.Collection"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceTypeName="Collection"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractD" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refToSomeA" lowerBound="1"
          eType="#//ntas/A" changeable="false" derived="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="attributes" nsURI="http://www.jastemf.org/test/attributes" nsPrefix="attributes"/>
</ecore:EPackage>
