/*
* generated by Xtext
*/
package org.jastemf.siple.ui.contentassist;

import org.jastemf.siple.ui.contentassist.AbstractSipleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SipleProposalProvider extends AbstractSipleProposalProvider {

}
