<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine"
    nsURI="http://www.jastemf.org/statemachine" nsPrefix="stm">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eAnnotations source="gmf.diagram">
      <details key="model.extension" value="sm"/>
      <details key="diagram.extension" value="smd"/>
    </eAnnotations>
    <eOperations name="printReachable" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Declaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true">
    <eOperations name="printReachable" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Declaration">
    <eAnnotations source="gmf.link">
      <details key="label" value="label, guardLabel, actionLabel"/>
      <details key="label.pattern" value="{0} [ {1} ] {2}"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="color" value="0.0.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//State"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardLabel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" eType="#//GuardExpression">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionExpression" eType="#//ActionExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Declaration">
    <eAnnotations source="gmf.node">
      <details key="label" value="label"/>
      <details key="label.icon" value="true"/>
      <details key="figure" value="rounded"/>
      <details key="border.color" value="0.0.0"/>
    </eAnnotations>
    <eOperations name="printReachable" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//State" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reachable" upperBound="-1"
        eType="#//State" transient="true" derived="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Action"
        containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eAnnotations source="gmf.node">
      <details key="label" value="actionLabel"/>
      <details key="label.icon" value="true"/>
      <details key="figure" value="rounded"/>
      <details key="border.color" value="255,255,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionExp" eType="#//ActionExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuardExpression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionExpression" abstract="true"/>
</ecore:EPackage>
